### PR TITLE
changed header for issue 54

### LINKED ISSUE #54: [Feature] - Modify table headers to support future sorting functionality
### Discussed in https://github.com/jdwilkin4/fcc-forum-clone/discussions/50

Add HTML and CSS to support future functionality to sort topics by number of replies, views and activity.

Change replies, views and activity headers' names to buttons to look something like this
```html
<th>
    <button name="sort" value="replies">Replies</button>
</th>
```
and add styles so it looks like in this [Figma prototype](https://www.figma.com/proto/UYXlxWMdsz5Z69WD1s4HK8/fcc-forum-table-(Copy)?node-id=202%3A3&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=202%3A3).

Notice how the styles change when you hover over the Activity header. That should apply to replies and views headers too.

You can try click on it and see what it does next, but don't worry about it now, it will be included in the next issues.

### PR DESCRIPTION
**Pull request by dgupta0**
# Description

Made changes for table header in index.html and index.css as per issue number 54. 
Fixes #54

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore items (this includes basic clean up of files, or updates to packages)
- [ ] Updates to documentation

## Checklist

- [x] I have a descriptive title for my PR
- [x] I have linked the issue to this [PR](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] I have run the project locally and reviewed the code changes
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Dorfieeee — CHANGES_REQUESTED** [review]
Good job!

Could you please add another CSS property so the cursor looks like this?
image

**Comment by dgupta0** [comment]
Oh, sorry! Totally forgot about that. Thanks. Will do it asap.

**Review by Dorfieeee — APPROVED** [review]
LGTM 👍

**Review by ChefDaddyJay — APPROVED** [review]
I don't see any problems :+1:

**Pull request merged**
