### PR TITLE
feat: forum fetch setup

### LINKED ISSUE #14: [Feature] - Setup fetch call with error handling and loading state
### What feature would you like to see?

**Please note: I would suggest working on this after #12 has been merged**

The goal of this ticket is to setup the basic fetch call for our forum API.
The `fetch` method returns a promise that will either be fulfilled or rejected. The initial state for the `fetch` call will be pending. 

We will need to create three variables.
One to check the current loading state which will have the value of a boolean. Ex. `isLoading=true`
One to check if there is an error fetching data. Ex. `isError=false`
One to set the data from the fetched results. Ex. `forumData`

If our fetch is successful, then we will want to save our json data to a variable, log a success message to the console and set our loading variable to false.
If our fetch failed, we will want to log that error to the console, set our error variable to true,  and set our loading variable to false.

For this ticket, don't worry about display loading, error messages or rendering the content to the page.
That will be taken care of in other tickets.

For now, just use console.logs for success and failed states. 

Here are some helpful articles on using the fetch API
https://gomakethings.com/how-to-use-the-fetch-api-with-vanilla-js/#the-basic-fetch-api-syntax
https://dmitripavlutin.com/javascript-fetch-async-await/

Also, don't worry about the optional options object that was mentioned in the articles. For this project, we won't need it.

### PR DESCRIPTION
**Pull request by Dorfieeee**
# Description

Basic setup with Fetch API to `fetch` latest FCC forum data.
- variables initialised with default states
- if response status OK, extract data, otherwise throw an error
- variables modified according to the result
- result and data print to the console

Fixes #14 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore items (this includes basic clean up of files, or updates to packages)
- [ ] Updates to documentation

## Checklist

- [x] I have a descriptive title for my PR
- [x] I have linked the issue to this [PR](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] I have run the project locally and reviewed the code changes
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by dgupta0** [comment]
Hi @Dorfieeee, 

I am not really familiar with API so I will try my best to understand what you are trying to do.
So, when I start npm then in the console I get the error - `Failed to load resource: the server responded with a status of 404 (Not Found)`
Not sure if that means couldn't load API. I don't know how to express it lol.

From the JS File, I think what you are doing is calling a function `Fetch_API` to get the data, and throwing error if the data not found. Else returning the data, which I can see in the object form. 

I am trying to understand now why the data is not rendering.  I am seeing the` innerText` property for the first time.

**Comment by Dorfieeee** [comment]
Hello @dgupta0,
The error is about missing favicon -- the icon displaying a browser's tab. The browser is trying to get it from path `/favicon.ico` but we have not added it yet.
image
Nothing is rendering because that's a job for the following issue #19.
You should only see the result of the `fetch()` in the console.

- I am calling `fetch` with the FCC forum url, which is stored in `FORUM_API` in `constants.js`.
`export const FORUM_API = "https://forum-proxy.freecodecamp.rocks/latest";`
- When the external server returns the [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) with code 200 => ok, I then parse the response to JSON format by calling `json()` on the Response object. When it is not ok, I throw an error with a message stored in the `Response.statusText`, which is caught and dealt with in the `catch` block. When you throw an error inside any of those `then` blocks, it will cancel its execution and jump right to the catch block.
- Once the data from the response are parsed I then display them in the console. This will be replaced by rendering it as table rows later.
- Finally, I set the `loading` to `false`. `finally` block is always executed. This way, I don't have to set the `loading` variable to `false` twice, in `then` and `catch` blocks. This may be changed later.

You may be wondering why do I return the `response.json` and then chaining another `then` block. The `json` method returns a Promise, just as the `fetch`. I resolve the Promise from `fetch` by chaining the first `then` where I return another Promise which is resolved by the other `then`.
```
fetch() returns Promise, when resolved -> jump to then block; rejected -> catch block
when the Promise from fetch is resolved, it returns Response object
.then(Response=> {
 return Response.json() => another Promise, when resolved, returns a standard JS object
}
.then(data => {
 do stuff
}
```

**Comment by dgupta0** [comment]
I can only understand that a lot is going on within a few lines of code  :)

**Comment by Dorfieeee** [comment]
@dgupta0 
How can I help you understand?
Let's forget about JavaScript for now.
Do you know about HTTP requests?
How are data transmitted across the network between your computer and a server?
What role does web browser have in all this?
If I can help you understand these things a little bit, the code will make more sense to you. In any programming language.
Great source on YouTube
https://www.youtube.com/playlist?list=PLRqwX-V7Uu6YxDKpFzf_2D84p0cyk4T7X

**Comment by dgupta0** [comment]
@Dorfieeee 
Thanks for staring the resource.  Currently I am following scrimba web dev path to learn front end. I am relying on their module to start with API's. If I get stuck I will ping you. I hope you will be available. 
And, I don't know about HTTP requests and data transmission.

**Pull request merged**
